# Generated by Django 6.0.4 on 2026-05-13 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=100, unique=True, verbose_name='Кадастровый номер')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь(га)')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('occupied', 'Занято')], default='free', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Карта полей',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вида')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('item_type', models.CharField(choices=[('seed', 'Семена'), ('fertilizer', 'Удобрения'), ('pesticide', 'Химикаты'), ('feed', 'Корма и добавки'), ('medicine', 'Вет препараты'), ('product_crop', 'Собранный урожай'), ('product_animal', 'Продукция животноводства'), ('fuel', 'ГСМ'), ('spare_part', 'Запчасти и расходники'), ('inventory', 'Хоз инвентарь')], max_length=20, verbose_name='Тип ресурса')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Количество')),
                ('unit', models.CharField(default='', help_text='кг, л , шт, тонн', max_length=10, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Склад / Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], max_length=1, verbose_name='Пол')),
                ('status', models.CharField(choices=[('healthy', 'Здоров'), ('quarantine', 'Карантин'), ('sick', 'Болен')], max_length=20, verbose_name='Статус')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.species', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(verbose_name='Дата посева')),
                ('harvest_planned', models.DateField(verbose_name='Прогноз сбора')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farm.field', verbose_name='Поле')),
                ('crop', models.ForeignKey(limit_choices_to={'item_type': 'seed'}, on_delete=django.db.models.deletion.PROTECT, to='farm.storage')),
            ],
            options={
                'verbose_name': 'Посев',
                'verbose_name_plural': 'Севооборот',
            },
        ),
        migrations.CreateModel(
            name='VeterinaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание мероприятия/диагноз')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Затраты')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='farm.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Вет. запись',
                'verbose_name_plural': 'Журнал ветеринара',
            },
        ),
    ]
