# Generated by Django 6.0.5 on 2026-06-01 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croprotation',
            options={'verbose_name': 'Посадка', 'verbose_name_plural': 'Севооборот'},
        ),
        migrations.AlterModelOptions(
            name='veterinarylog',
            options={'verbose_name': 'Вет. запись', 'verbose_name_plural': 'Ветеринарный журнал'},
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='harvest_planned',
            field=models.DateField(verbose_name='Плановая уборка'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='item_type',
            field=models.CharField(choices=[('seed', 'Семена'), ('fertilizer', 'Удобрения'), ('pesticide', 'Пестициды'), ('feed', 'Корма / Добавки'), ('medicine', 'Вет. препараты'), ('product_crop', 'Растительная продукция'), ('product_animal', 'Продукция животноводства'), ('fuel', 'Топливо'), ('spare_part', 'Запчасти и материалы'), ('inventory', 'Инвентарь')], max_length=20, verbose_name='Тип ресурса'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='unit',
            field=models.CharField(default='', help_text='кг, л, шт, меш', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='veterinarylog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='veterinarylog',
            name='description',
            field=models.TextField(verbose_name='Описание процедуры/диагноз'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход'), ('logout', 'Выход'), ('other', 'Другое')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Представление объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали (JSON)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись действия',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-timestamp'],
            },
        ),
    ]
