# Generated by Django 6.0.5 on 2026-06-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_croprotation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='crop',
            field=models.ForeignKey(limit_choices_to={'item_type': 'seed'}, on_delete=django.db.models.deletion.PROTECT, to='farm.storage', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='field',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (га)'),
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('feeding', 'Кормление'), ('cleaning', 'Уборка/Чистка'), ('milking', 'Дойка'), ('weighing', 'Взвешивание'), ('watering', 'Полив'), ('harvesting', 'Сбор урожая'), ('planting', 'Посадка'), ('treatment', 'Обработка'), ('moving', 'Перемещение'), ('other', 'Другое')], max_length=20, verbose_name='Тип действия')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='Тип объекта')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='Объект')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Объём (кг/л/шт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись в журнале работ',
                'verbose_name_plural': 'Журнал работ',
                'ordering': ['-created_at'],
            },
        ),
    ]
