# Generated by Django 6.0.5 on 2026-06-01 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_animal_responsible_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('procedure_type', models.CharField(choices=[('vaccination', 'Вакцинация'), ('examination', 'Плановый осмотр'), ('treatment', 'Лечение'), ('testing', 'Анализы/Диагностика'), ('deworming', 'Дегельминтизация'), ('castration', 'Кастрация'), ('other', 'Другое')], max_length=20, verbose_name='Тип процедуры')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Инструкции')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ориентировочная стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_plans', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vet_plans', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('species', models.ForeignKey(blank=True, help_text='Оставьте пустым, если для всех видов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.species', verbose_name='Группа (вид животных)')),
            ],
            options={
                'verbose_name': 'План вет. мероприятия',
                'verbose_name_plural': 'Планы ветеринарных осмотров',
                'ordering': ['planned_date', 'title'],
            },
        ),
    ]
