# Generated by Django 6.0.5 on 2026-06-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_vetplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('supplier', models.CharField(choices=[('agro_plus', 'АгроПлюс'), ('fermer_trade', 'ФермерТрейд'), ('vet_pharm', 'ВетФарм'), ('seed_house', 'Семенной Дом'), ('local', 'Местный поставщик'), ('other', 'Другой')], max_length=30, verbose_name='Поставщик')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер накладной')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата закупки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='farm.storage', verbose_name='Ресурс')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто закупил')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки ресурсов',
                'ordering': ['-created_at'],
            },
        ),
    ]
