# Generated by Django 6.0.5 on 2026-06-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу (₽)')),
                ('buyer', models.CharField(max_length=255, verbose_name='Покупатель')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('completed', 'Реализована'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кто оформил')),
                ('item', models.ForeignKey(limit_choices_to={'item_type__in': ['product_crop', 'product_animal']}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='farm.storage', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Заявка на продажу',
                'verbose_name_plural': 'Заявки на продажу',
                'ordering': ['-created_at'],
            },
        ),
    ]
