# Generated by Django 6.0.5 on 2026-06-01 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_saleorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croprotation',
            options={'verbose_name': 'Запись севооборота', 'verbose_name_plural': 'Севооборот'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Поле', 'verbose_name_plural': 'Сельхозполя'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки товаров'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ на продажу', 'verbose_name_plural': 'Продажи продукции'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Склад / Запасы'},
        ),
        migrations.AlterModelOptions(
            name='vetplan',
            options={'ordering': ['planned_date', 'title'], 'verbose_name': 'Вет. план процедуры', 'verbose_name_plural': 'Ветеринарные планы работ'},
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='harvest_planned',
            field=models.DateField(verbose_name='Плановый сбор'),
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='planting_date',
            field=models.DateField(verbose_name='Дата посадки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='farm.storage', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто приобрёл'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу (руб)'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='item_type',
            field=models.CharField(choices=[('seed', 'Семена'), ('fertilizer', 'Удобрения'), ('pesticide', 'Пестициды'), ('feed', 'Корма / Подкормка'), ('medicine', 'Вет. препараты'), ('product_crop', 'Растениеводческая продукция'), ('product_animal', 'Продукция животноводства'), ('fuel', 'Топливо'), ('spare_part', 'Запчасти и инструменты'), ('inventory', 'Инвентарь')], max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='unit',
            field=models.CharField(default='шт', help_text='кг, л, шт, доз', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='veterinarylog',
            name='description',
            field=models.TextField(verbose_name='Описание процедуры/диагноза'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vet_plans', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание / Инструкция'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предполагаемая стоимость'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='procedure_type',
            field=models.CharField(choices=[('vaccination', 'Вакцинация'), ('examination', 'Плановый осмотр'), ('treatment', 'Лечение'), ('testing', 'Анализ/Диагностика'), ('deworming', 'Дегельминтизация'), ('castration', 'Кастрация'), ('other', 'Другое')], max_length=20, verbose_name='Тип процедуры'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если для всех видов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.species', verbose_name='Вид (группа животных)'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vetplan',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название процедуры'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='action_type',
            field=models.CharField(choices=[('feeding', 'Кормление'), ('cleaning', 'Уборка/Чистка'), ('milking', 'Доение'), ('weighing', 'Взвешивание'), ('watering', 'Полив'), ('harvesting', 'Сбор урожая'), ('planting', 'Посадка'), ('treatment', 'Обработка'), ('moving', 'Перемещение'), ('other', 'Другое')], max_length=20, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
